### ISSUE TITLE
"Driver_Notes/EULA" was added to the "msedgedriver" package, which broke the driver install script.

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1006]
"Driver_Notes/EULA" was added to the "msedgedriver" package, which broke ``sbase install edgedriver``.
SeleniumBase keeps a manifest of all files that should be in the packaging of drivers, so if a file changes (is added or removed), then the install script breaks because it doesn't know how to handle that file. To fix this, "Driver_Notes/EULA" should be added to the list of files to expect in the packaging of "msedgedriver".

Here's the stack trace from ``sbase install edgedriver``:

```bash
sbase install edgedriver

*** edgedriver version for download = 94.0.992.38

Downloading edgedriver_mac64.zip from:
https://msedgedriver.azureedge.net/94.0.992.38/edgedriver_mac64.zip ...
Download Complete!

Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase9/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/run.py", line 719, in main
    sb_install.main()
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/sb_install.py", line 591, in main
    raise Exception(
Exception: Expected file [Driver_Notes/EULA] missing from [['Driver_Notes/', 'Driver_Notes/LICENSE', 'Driver_Notes/credits.html', 'msedgedriver', 'libc++.dylib']]
```

**Comment by mdmintz** [comment]
Fixed in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.66.10
