### ISSUE TITLE
Unable to install edge driver

### ISSUE THREAD

**Issue by sohilluhar** [seleniumbase/SeleniumBase#1012]
cmd run:
sbase install edgedriver

Log---
Downloading edgedriver_win32.zip from:
https://msedgedriver.azureedge.net/94.0.992.47/edgedriver_win32.zip ...
Download Complete!

Traceback (most recent call last):
File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\XYZ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\XYZ\PycharmProjects\pythonProject phase 1\venv\Scripts\sbase.exe\__main__.py", line 7, in <module>
File "c:\users\XYZ\pycharmprojects\pythonproject phase 1\venv\lib\site-packages\seleniumbase\console_scripts\run.py", line 718, in main
sb_install.main()
File "c:\users\XYZ\pycharmprojects\pythonproject phase 1\venv\lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 591, in main
raise Exception(
Exception: Expected file [Driver_Notes/EULA] missing from [['Driver_Notes/', 'Driver_Notes/credits.html', 'Driver_Notes/LICENSE', 'msedgedriver.exe']]

**Comment by mdmintz** [comment]
@sohilluhar Microsoft changed how they packaged EdgeDriver (they added a EULA file inside, which broke the installer). A fix was shipped in https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.66.10

```
sbase install edgedriver

*** edgedriver version for download = 94.0.992.47

Downloading edgedriver_mac64.zip from:
https://msedgedriver.azureedge.net/94.0.992.47/edgedriver_mac64.zip ...
Download Complete!

Driver_Notes/
Driver_Notes/LICENSE
Driver_Notes/EULA
Driver_Notes/credits.html
msedgedriver
Extracting ['Driver_Notes/', 'Driver_Notes/LICENSE', 'Driver_Notes/EULA', 'Driver_Notes/credits.html', 'msedgedriver'] from edgedriver_mac64.zip ...
Unzip Complete!

The file [msedgedriver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/msedgedriver

Making [msedgedriver 94.0.992.47] executable ...
[msedgedriver] is now ready for use!
```

Upgrade to the latest SeleniumBase for the fix.
