### ISSUE TITLE
class name scrolling

### ISSUE THREAD

**Issue by LeaDer-E** [seleniumbase/SeleniumBase#1231]
**hello, can i get small help :rose:** 
**just need to know how can i scrolling down but onle with class name** 

```
<div data-is-here-when="md lg" class="left-sidebar js-pinned-left-sidebar ps-relative" id="left-sidebar">
    <div class="left-sidebar--sticky-container js-sticky-leftnav">
```

![Screenshot at 2022-02-22 02-16-59](https://user-images.githubusercontent.com/99460904/155042658-ce98b313-7feb-49c4-bdbe-e2b1be845fb7.png)

**Comment by mdmintz** [comment]
The basic method for scrolling to an element is:
self.scroll_to(selector)
For classname, use “.CLASS” as the CSS Selector.

**Comment by LeaDer-E** [comment]
still have a problem 

```
driver.get("https://stackoverflow.com/questions/20986631/how-can-i-scroll-a-web-page-using-selenium-webdriver-in-python")
#selector = driver.find_element_by_class_name("left-sidebar js-pinned-left-sidebar ps-relative")
selector = driver.find_element(By.CLASS_NAME, "left-sidebar js-pinned-left-sidebar ps-relative")
self.scroll_to(selector)
```

output:

```
======== RESTART: /home/eslammustafa/Desktop/PY Projects/0koko (copy).py =======

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 89
    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!

Warning (from warnings module):
  File "/home/eslammustafa/Desktop/PY Projects/0koko (copy).py", line 47
    driver = webdriver.Chrome(executable_path="/home/eslammustafa/Desktop/PY Projects/chromedriver")
DeprecationWarning: executable_path has been deprecated, please pass in a Service object
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/eslammustafa/Desktop/PY Projects/0koko (copy).py", line 65, in <module>
    selector = driver.find_element(By.CLASS_NAME, "left-sidebar js-pinned-left-sidebar ps-relative")
  File "/home/eslammustafa/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/eslammustafa/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/eslammustafa/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".left-sidebar js-pinned-left-sidebar ps-relative"}
  (Session info: chrome=98.0.4758.102)
Stacktrace:
#0 0x55e612849b33 <unknown>
#1 0x55e6123126d8 <unknown>
#2 0x55e6123486f1 <unknown>
#3 0x55e6123488b1 <unknown>
#4 0x55e61237b574 <unknown>
#5 0x55e61236608d <unknown>
#6 0x55e6123792fb <unknown>
#7 0x55e612365f53 <unknown>
#8 0x55e61233ba0a <unknown>
#9 0x55e61233cad5 <unknown>
#10 0x55e61287b2fd <unknown>
#11 0x55e6128944bb <unknown>
#12 0x55e61287d0d5 <unknown>
#13 0x55e612895145 <unknown>
#14 0x55e612870aaf <unknown>
#15 0x55e6128b1ba8 <unknown>
#16 0x55e6128b1d28 <unknown>
#17 0x55e6128cc48d <unknown>
#18 0x7f721ebe8609 <unknown>
```

**Comment by mdmintz** [comment]
Use a CSS Selector instead. A classname cannot contain spaces.

**Comment by LeaDer-E** [comment]
```
    self.scroll_to(selector)
NameError: name 'self' is not defined
```

**Comment by mdmintz** [comment]
In order to use SeleniumBase methods, your class must inherit BaseCase. Look over the examples.
