### ISSUE TITLE
msedgedriver download issue on M1/M2 Macs

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1612]
### ``msedgedriver`` download issue on M1/M2 Macs

(This was a regression in version ``4.8.3``)

Stacktrace:

```
Warning: msedgedriver version doesn't match Edge version!
Attempting to install a matching version of msedgedriver:

Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase11b/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/run.py", line 974, in main
    sb_install.main()
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/sb_install.py", line 405, in main
    and int(use_version) > 104
        ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '107.0.1418.42'
```

Need to convert the full version to an int before making the comparison.

Eg: ``107.0.1418.42`` to ``107``.

**Comment by mdmintz** [comment]
Released in ``4.8.5`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.8.5
