### ISSUE TITLE
Chromedriver changed packaging in version 109, leading to a failed download and duplicate attempts

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1663]
Chromedriver changed packaging in version 109, leading to a failed download and duplicate attempts.

They added this file: ``LICENSE.chromedriver`` on a Mac (and probably the equivalent license file on other systems). SeleniumBase was currently only programmed to accept zip files that had exactly the expected contents, but now there's a need to allow variations of that zip file if they add additional files in there, like that license one.

```bash
sbase install chromedriver 109

*** chromedriver version for download = 109.0.5414.74 (Latest)

Downloading chromedriver_mac_arm64.zip from:
https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_mac_arm64.zip ...
Download Complete!


* Unable to download driver! Retrying in 3s...


*** chromedriver version for download = 109.0.5414.74 (Latest)

Downloading chromedriver_mac_arm64.zip from:
https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_mac_arm64.zip ...
Download Complete!

** Unable to download driver! Retrying in 5s...


*** chromedriver version for download = 109.0.5414.74 (Latest)

Downloading chromedriver_mac_arm64.zip from:
https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_mac_arm64.zip ...
Download Complete!

Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase11e/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/run.py", line 977, in main
    sb_install.main()
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/sb_install.py", line 835, in main
    raise Exception("Expecting only one file in %s!" % zip_file_path)
Exception: Expecting only one file in /Users/michael/github/SeleniumBase/seleniumbase/drivers/chromedriver_mac_arm64.zip!
```

**Comment by mdmintz** [comment]
Released in ``4.11.3`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.3
