### ISSUE TITLE
Multithreading log dir problem

### ISSUE THREAD

**Issue by naueramant** [seleniumbase/SeleniumBase#171]
when i run nosetests with multiple process and two browser (chrome and firefox) on a selenium grid with chrome-node and firefox-node i get this error:

```
nose.plugins.multiprocess: ERROR: Worker 0 error running test or returning results
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/local/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.6/unittest/case.py", line 613, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/local/lib/python3.6/unittest/case.py", line 543, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/usr/local/lib/python3.6/site-packages/nose/proxy.py", line 131, in addError
    plugins.addError(self.test, err)
  File "/usr/local/lib/python3.6/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/lib/python3.6/site-packages/nose/plugins/manager.py", line 334, in addError
    return self.plugin.addError(test.test, err, capt)
  File "/usr/local/lib/python3.6/site-packages/seleniumbase/plugins/base_plugin.py", line 155, in addError
    self.__log_all_options_if_none_specified(test)
  File "/usr/local/lib/python3.6/site-packages/seleniumbase/plugins/base_plugin.py", line 111, in __log_all_options_if_none_specified
    test, test_logpath, test.driver, test.browser)
  File "/usr/local/lib/python3.6/site-packages/seleniumbase/core/log_helper.py", line 22, in log_test_failure_data
    log_file = codecs.open(basic_file_path, "w+", "utf-8")
  File "/usr/local/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'latest_logs/<test name>/basic_test_info.txt'
```

Maybe the log_helper do not handle the preparation of the folder probably?

**Comment by mdmintz** [comment]
Hi @naueramant,
Are you using ``--processes=NUM`` for running tests multithreaded with nosetests? I was looking into https://github.com/nose-devs/nose/issues and it seems the creators of Nose have stopped supporting it in favor of Pytest. I've maintained Nose compatibility with SeleniumBase, although a few things like Nosetest multi-threading may have issues. Pytest is the SeleniumBase standard for running tests (as Pytest is actively being supported by its developers) and all multi-threaded functions should be fully compatible with that. You should be able to swap ``nosetests`` with ``pytest`` in your run command, and then use ``-n=NUM`` instead of ``--processes=NUM`` to run tests with Pytest multi-threaded. Are you able to do that? In the near future, I plan to override the existing Nosetest multi-threading plugin with a new one to get around issues that people may be experiencing (for those that are still using Nosetests instead of Pytest).

**Comment by naueramant** [comment]
Yes i should be able to switch to pytest instead thanks for the quick reply!

**Comment by naueramant** [comment]
Switching to pytest solved everything. Much better documentation as well thanks for the advice. Maybe a warning about nosetest or removal of nosetest from seleniumbase documentation would be a good idea?

**Comment by mdmintz** [comment]
Awesome! I'll to try to phase out Nosetests in favor of Pytest, or at least put up warnings about Nosetest compatibility. For the Multi-threading issues with Nosetests, I'll try to override the multi-threading option so that it forces a single-threaded run, which won't have issues. It'll be a good weekend project for me.

**Comment by mdmintz** [comment]
Let me know if you have any more SeleniumBase questions!
