### ISSUE TITLE
How to use SeleniumBase like Selenim for no-test cases

### ISSUE THREAD

**Issue by alimp5** [seleniumbase/SeleniumBase#1884]
I tried to write a simple web bot like selenium. but i think your framework  work in another way.
when i wrote `MyTestClass().test_anything()`, i got error below. but if i comment-out this line, script work without problem and run an instance of browser  and do something .....

I think your framework just work for testing (https://seleniumbase.io/help_docs/features_list/).

how to use it like python selenium !.?

```
Traceback (most recent call last):
  File "c:/Users/linux-11/Desktop/seleniumBase_test.py", line 29, in <module>
    MyTestClass().test_anything()
  File "c:/Users/linux-11/Desktop/seleniumBase_test.py", line 24, in test_anything
    self.open("https://github.com/")
  File "C:\Python38\lib\site-packages\seleniumbase\fixtures\base_case.py", line 210, in open
    self.__check_scope()
  File "C:\Python38\lib\site-packages\seleniumbase\fixtures\base_case.py", line 9845, in __check_scope
    raise OutOfScopeException(message)
seleniumbase.common.exceptions.OutOfScopeException:
 It looks like you are trying to call a SeleniumBase method
 from outside the scope of your test class's `self` object,
 which is initialized by calling BaseCase's setUp() method.
 The `self` object is where all test variables are defined.
 If you created a custom setUp() method (that overrided the
 the default one), make sure to call super().setUp() in it.
 When using page objects, be sure to pass the `self` object
 from your test class into your page object methods so that
 they can call BaseCase class methods with all the required
 variables, which are initialized during the setUp() method
 that runs automatically before all tests called by pytest.
```

```
from seleniumbase import Driver, BaseCase
# BaseCase.main(__name__, __file__)

from seleniumbase import BaseCase
class MyTestClass(BaseCase):
    def test_anything(self):
        self.open("https://github.com/")
        self.type("input.header-search-input", "SeleniumBase\n")
        self.click('a[href="/seleniumbase/SeleniumBase"]')

MyTestClass().test_anything()     ### comment / un-comment.
```

**Comment by mdmintz** [comment]
See https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md#sb_sf_21 for one of a few different ways of using SeleniumBase without a test runner.
