### ISSUE TITLE
If Chrome 115: "sbase get chromedriver" fails with "Could not find chromedriver to download!"

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#1969]
## If Chrome 115: "sbase get chromedriver" fails with "Could not find chromedriver to download!"

This is related to https://github.com/seleniumbase/SeleniumBase/issues/1968 and https://github.com/seleniumbase/SeleniumBase/issues/1966, where new drivers are no longer on https://chromedriver.chromium.org/downloads.

Until the Chromium Team resolves https://bugs.chromium.org/p/chromium/issues/detail?id=1466427, it's best to set chromedriver 114 as the maximum version for download, (and to keep using it for Chrome 115+).

Note: This only impacts running ``sbase get chromedriver`` on the command-line. SeleniumBase tests already have the fix from https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.16.1 to automatically take this into account.

--------

```bash
sbase get chromedriver

* Unable to download driver! Retrying in 3s...

** Unable to download driver! Retrying in 5s...

Traceback (most recent call last):
  File "/Users/michael/.virtualenvs/sbase/bin/sbase", line 33, in <module>
    sys.exit(load_entry_point('seleniumbase', 'console_scripts', 'sbase')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/run.py", line 1007, in main
    sb_install.main()
  File "/Users/michael/github/SeleniumBase/seleniumbase/console_scripts/sb_install.py", line 362, in main
    raise Exception("Could not find chromedriver to download!\n")
Exception: Could not find chromedriver to download!
```

**Comment by mdmintz** [comment]
This was resolved in ``4.16.2`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.16.2
