### ISSUE TITLE
can i connect to Remote with SeleniumBase?

### ISSUE THREAD

**Issue by YOTYTeaM** [seleniumbase/SeleniumBase#2071]
can i connect to Remote with SeleniumBase?
im using `SB`

i mean
```
from selenium.webdriver import Remote

driver = Remote(url, options=options)
```
like that but with `SB`

**Comment by mdmintz** [comment]
With `SB`, here's an example of using the `remote` browser, which is specific to using a Selenium Grid, and also requires a capabilities file (https://github.com/seleniumbase/SeleniumBase/tree/master/examples/capabilities):

```python
from seleniumbase import SB

with SB(browser="remote", servername="USERNAME:KEY@hub.browserstack.com", port="80", cap_file="capabilities/sample_cap_file_BS.py") as sb:
    sb.open("https://seleniumbase.io/realworld/login")
    sb.type("#username", "demo_user")
    sb.type("#password", "secret_pass")
    sb.enter_mfa_code("#totpcode", "GAXG2MTEOR3DMMDG")  # 6-digit
    sb.assert_text("Welcome!", "h1")
    sb.highlight("img#image1")  # A fancier assert_element() call
    sb.click('a:contains("This Page")')  # Use :contains() on any tag
    sb.click_link("Sign out")  # Link must be "a" tag. Not "button".
    sb.assert_element('a:contains("Sign in")')
    sb.assert_exact_text("You have been signed out!", "#top_message")
```

**Comment by YOTYTeaM** [comment]
i got an error
using MultiLogin mimic(chrome)


cap.py:
```
capabilities = {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'goog:chromeOptions': {'extensions': [], 'args': []}}
```

and the main code:
```
with SB(
        browser="remote",
        servername='http://127.0.0.1',
        port=port,
        cap_file='cap.py'
    )as sb:
    # other codes
```
    
    
got this error:
```
    Traceback (most recent call last):
  File "P:/projects/X/main.py", line 225, in make
    gmail, password = ws(remote_url, port, recovery_gmail)
  File "P:\projects\X\webScrapingRemote.py", line 253, in ws
    with SB(
  File "C:\Users\atila\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "P:\projects\X\venv\lib\site-packages\seleniumbase\plugins\sb_manager.py", line 843, in SB
    sb.setUp()
  File "P:\projects\X\venv\lib\site-packages\seleniumbase\fixtures\base_case.py", line 14205, in setUp
    self.driver = self.get_new_driver(
  File "P:\projects\X\venv\lib\site-packages\seleniumbase\fixtures\base_case.py", line 3849, in get_new_driver
    new_driver = browser_launcher.get_driver(
  File "P:\projects\X\venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 1308, in get_driver
    return get_remote_driver(
  File "P:\projects\X\venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 1967, in get_remote_driver
    return webdriver.Remote(
  File "P:\projects\X\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "P:\projects\X\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "P:\projects\X\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "P:\projects\X\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown command: unknown command: wd/hub/session
Stacktrace:
  GetHandleVerifier [0x00007FF7A77DAEE2+118978]
  (No symbol) [0x00007FF7A7738562]
  (No symbol) [0x00007FF7A75EC82B]
  (No symbol) [0x00007FF7A7644E6E]
  (No symbol) [0x00007FF7A7644660]
  (No symbol) [0x00007FF7A75C42B0]
  GetHandleVerifier [0x00007FF7A7B5EDE2+3805122]
  GetHandleVerifier [0x00007FF7A7B6B504+3856100]
  GetHandleVerifier [0x00007FF7A7B6448F+3827311]
  GetHandleVerifier [0x00007FF7A790ADA6+1363846]
  (No symbol) [0x00007FF7A7743E48]
  (No symbol) [0x00007FF7A75C3125]
  GetHandleVerifier [0x00007FF7A7B9ECF8+4067032]
  BaseThreadInitThunk [0x00007FFC083A26AD+29]
  RtlUserThreadStart [0x00007FFC0A06AA68+40]
```

**Comment by mdmintz** [comment]
Not all Selenium Grids support `browser="remote"`. Use a direct browser (eg. `browser="chrome"`) if your Grid doesn't support `remote`.

**Comment by YOTYTeaM** [comment]
is there any method to use Remote.
for example change driver in BaseCase to Remote driver
