### ISSUE TITLE
TypeError: Binary Location Must be a String

### ISSUE THREAD

**Issue by iamumairayub** [seleniumbase/SeleniumBase#2284]
I have simple code where I want to use UC mode but I am getting this error.

```
from seleniumbase import Driver
import time

driver = Driver(
    uc=True,
    )
driver.get("https://nowsecure.nl/#relax")
time.sleep(6)
driver.quit()
```

```
root@Scrapers:/home/scrapers_dev# python seleniumbase_test.py
Traceback (most recent call last):
  File "/home/scrapers_dev/selenoid_test.py", line 4, in <module>
    driver = Driver(uc=True, incognito=True)
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/plugins/driver_manager.py", line 463, in Driver
    driver = browser_launcher.get_driver(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/core/browser_launcher.py", line 1561, in get_driver
    return get_local_driver(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/core/browser_launcher.py", line 3390, in get_local_driver
    driver = undetected.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/seleniumbase/undetected/__init__.py", line 217, in __init__
    options.binary_location = (
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

```

I have installed seleniumbase just today using `pip install seleniumbase` command. Also tried `pip install seleniumbase --upgrade` but no help.

**python -V**
`Python 3.10.7`
**pip -V**
`pip 23.3.1 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)`
**lsb_release -a**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Comment by mdmintz** [comment]
It means Chrome wasn't found on your system, or it wasn't in the expected location.

https://github.com/seleniumbase/SeleniumBase/blob/5f68c82ccc589ee5e85df37d0a0a1581a0acc55e/seleniumbase/core/detect_b_ver.py#L212

You can try it yourself:

```python
from seleniumbase.core import detect_b_ver
print(detect_b_ver.get_binary_location("google-chrome"))
```

If Chrome isn't installed, be sure to install it first.

Or if Chrome isn't in the expected location, then set `binary_location` when calling `driver = Driver()`.

**Comment by iamumairayub** [comment]
Chrome is there, but still I get that same error.

```
Python 3.10.7 (main, Sep  7 2022, 15:22:19) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from seleniumbase.core import detect_b_ver
>>> print(detect_b_ver.get_binary_location("google-chrome"))
/usr/bin/google-chrome
```

I tried 

```
driver = Driver(
    uc=True,
    binary_location=r'/usr/bin/google-chrome'
    )
```

And error is same.
