### ISSUE TITLE
MacOS Message: Can not connect to the Service

### ISSUE THREAD

**Issue by fyxtc** [seleniumbase/SeleniumBase#2308]
`driver = Driver()`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3446, in get_local_driver
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    raise WebDriverException(f"Can not connect to the Service {self._path}")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/chromedriver

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hikaru/work/soulmanga/jm.py", line 7, in <module>
    driver = Driver(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 463, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1561, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3756, in get_local_driver
    driver = webdriver.Chrome(service=service)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    raise WebDriverException(f"Can not connect to the Service {self._path}")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/chromedrive`

It worked before, but not after restarting the computer.

**Comment by fyxtc** [comment]
ll /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/chromedriver
-rwxr-xr-x  1 hikaru  admin    17M 11 22 17:57 /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/chromedriver

**Comment by fyxtc** [comment]
Solved, add 127.0.0.1   localhost to /etc/hosts
