### ISSUE TITLE
Unable to obtain driver for chrome using Selenium Manager

### ISSUE THREAD

**Issue by harpreetrandhawa** [seleniumbase/SeleniumBase#2374]
>>> from seleniumbase import Driver
>>> Driver(browser= 'chrome', incognito= False, headless= True, uc=None)
Traceback (most recent call last):
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 137, in run
    output = json.loads(stdout)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 103, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 140, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 463, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1562, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3745, in get_local_driver
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by mdmintz** [comment]
SeleniumBase doesn't use the Selenium Manager for driver management. It has it's own driver manager that automatically downloads the driver you need if it's not found or is out-of-date. (Assuming that you have an internet connection.)

```python
from seleniumbase import Driver

driver = Driver(browser="chrome", incognito=False, headless=True)
driver.quit()
```

When running that without a driver, I see:

```python
Warning: chromedriver not found. Getting it now:

*** chromedriver to download = 120.0.6099.109 (Latest Stable) 

Downloading chromedriver-mac-arm64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-mac-arm64.zip ...
Unzip Complete!

The file [chromedriver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/chromedriver

Making [chromedriver 120.0.6099.109] executable ...
[chromedriver 120.0.6099.109] is now ready for use!
```

When running the script with an out-of-date driver, I see:

```python
Warning: chromedriver update needed. Getting it now:

*** chromedriver to download = 120.0.6099.109 (Latest Stable) 

Downloading chromedriver-mac-arm64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-mac-arm64.zip ...
Unzip Complete!

The file [chromedriver] was saved to:
/Users/michael/github/SeleniumBase/seleniumbase/drivers/chromedriver

Making [chromedriver 120.0.6099.109] executable ...
[chromedriver 120.0.6099.109] is now ready for use!
```

Based on your output, it looks like you either weren't connected to the internet when you ran your script, or your network has a firewall that is preventing the download of drivers. Selenium Manager isn't part of SeleniumBase (because it has it's own driver manager). If your issue is specifically with Selenium Manager, then you should reach out directly to the Selenium org: https://github.com/SeleniumHQ/selenium. If your issue is with SeleniumBase, check your internet connection and firewall rules.

**Comment by harpreetrandhawa** [comment]
I'm running this on ubuntu EC2 server: Fully connected with internet.

here is what I'm getting when running on the server Python3:

Python 3.11.1 (main, Nov 30 2023, 12:03:12) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from seleniumbase import Driver
>>> driver = Driver(browser="chrome", incognito=False, headless=True)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 137, in run
    output = json.loads(stdout)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 103, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 140, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 463, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1562, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/home/harpreet.singh1/.local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3745, in get_local_driver
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
>>>
