### ISSUE TITLE
On macOS, Chrome 120+, UC Mode, and Headless Mode, the browser gets stuck after script ends

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2375]
### On macOS, Chrome 120+, UC Mode, and Headless Mode, the browser gets stuck after the script tries to quit the browser at the end.

(When **ALL** of those settings are combined, that leads to the issue where the driver/browser gets stuck during the `quit()` process.)

This is likely caused by a change in Chrome 120 / chromedriver 120, where `os.waitpid()` isn't getting the same result anymore when the browser process is terminated:

https://github.com/seleniumbase/SeleniumBase/blob/570910c6f6e079cddd00c23e826e202c6489f39e/seleniumbase/undetected/__init__.py#L450

The stack trace confirms it:

```
Traceback (most recent call last):
  File "/Users/michael/github/SeleniumBase/examples/raw_uc_mode.py", line 4, in <module>
    with SB(uc=True, test=True, headless=True) as sb:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/michael/github/SeleniumBase/seleniumbase/plugins/sb_manager.py", line 924, in SB
    sb.tearDown()
  File "/Users/michael/github/SeleniumBase/seleniumbase/fixtures/base_case.py", line 15997, in tearDown
    self.__quit_all_drivers()
  File "/Users/michael/github/SeleniumBase/seleniumbase/fixtures/base_case.py", line 14952, in __quit_all_drivers
    driver.quit()
  File "/Users/michael/github/SeleniumBase/seleniumbase/undetected/__init__.py", line 450, in quit
    os.waitpid(self.browser_pid, 0)
KeyboardInterrupt
```

Currently have to use CTRL+C to terminate the script from the console.

**Comment by mdmintz** [comment]
This was resolved by `4.22.1` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.22.1
