### ISSUE TITLE
UC mode not worked, not load target page 

### ISSUE THREAD

**Issue by Vai3soh** [seleniumbase/SeleniumBase#2431]
Hello.

I use:
```
from seleniumbase import SB
import time
import os 
   
path = os.getcwd() + '/' + 'chromium'

chrome_options = "--incognito, --start-maximized"
with SB(uc=True, binary_location=path, chromium_arg=chrome_options, headless=False, headed=True) as sb: #
    sb.driver.get("https://nowsecure.nl/#relax")
    sb.sleep(1)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        sb.get_new_driver(undetectable=True)
        sb.driver.get("https://nowsecure.nl/#relax")
        sb.sleep(1)
    if not sb.is_text_visible("OH YEAH, you passed!", "h1"):
        if sb.is_element_visible('iframe[src*="challenge"]'):
            with sb.frame_switch('iframe[src*="challenge"]'):
                sb.click("span.mark")
                sb.sleep(2)
    sb.activate_demo_mode()
    sb.sleep(30)
    sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)

```

This launches two windows that are waiting for the checkbox to be clicked. And we get an error because we can't find the text

```
Traceback (most recent call last):
  File "/media/user/github.com/Vai3soh/cursor_reger/reger3.py", line 22, in <module>
    sb.assert_text("OH YEAH, you passed!", "h1", timeout=3)
  File "/home/user/.virtualenvs/env_cursor_reger/lib/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 9446, in assert_text
    self.wait_for_text_visible(text, selector, by=by, timeout=timeout)
  File "/home/user/.virtualenvs/env_cursor_reger/lib/python3.11/site-packages/seleniumbase/fixtures/base_case.py", line 9298, in wait_for_text_visible
    return page_actions.wait_for_text_visible(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/env_cursor_reger/lib/python3.11/site-packages/seleniumbase/fixtures/page_actions.py", line 633, in wait_for_text_visible
    timeout_exception(TextNotVisibleException, message)
  File "/home/user/.virtualenvs/env_cursor_reger/lib/python3.11/site-packages/seleniumbase/fixtures/page_actions.py", line 266, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.TextNotVisibleException: 
 Expected text substring {OH YEAH, you passed!} for {h1} was not visible after 3 seconds!
 (Actual string found was {nowsecure.nl})
```
The page you're looking for does appear when the script completes. While we are using the script this does not work (not load page nowsecure.nl).

**Comment by mdmintz** [comment]
UC Mode requires Chrome, not Chromium. Although Chrome is based on Chromium, the two are built differently.

You might also need a longer `reconnect_time`, based on your internet connection speed.
Here's an example of customizing that when opening a URL:

```python
sb.driver.uc_open_with_reconnect("https://nowsecure.nl/#relax", reconnect_time=5)
```
