### ISSUE TITLE
SeleniumBase driver version 

### ISSUE THREAD

**Issue by makarworld** [seleniumbase/SeleniumBase#2439]
I have chrome 120 version and when i trying to run seleniumbase driver i got error
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 120.0.6099.217 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
```

as solution driver should be downloaded from https://googlechromelabs.github.io/chrome-for-testing/

**Comment by mdmintz** [comment]
Without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your code, I cannot help you.

It looks like you weren't using SeleniumBase at all based on your error message. SeleniumBase automatically downloads a driver to match your browser version, and it also allows mismatched browser-driver pairings. Both of those are contrary to your output.

Be sure you are properly using one of the [23 Syntax Formats](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) when structuring your SeleniumBase tests.

**Comment by mdmintz** [comment]
You're using incorrect syntax. Here's the correct syntax:

```python
from seleniumbase import SB

with SB() as sb:
    sb.driver.get("https://google.com")
```

OR

```python
from seleniumbase import Driver

driver = Driver()
driver.get("https://google.com")
```

**Comment by makarworld** [comment]
same error

```
DevTools listening on ws://127.0.0.1:62035/devtools/browser/44edfda9-8471-44e5-b080-4e7a1be1080d
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3123, in get_local_driver
    driver = webdriver.Chrome(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=120.0.6099.217)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0083A813+48355]
        (No symbol) [0x007CC4B1]
        (No symbol) [0x006D5358]
        (No symbol) [0x006D85B5]
        (No symbol) [0x006D99E1]
        (No symbol) [0x006D9A80]
        (No symbol) [0x00721F1B]
        (No symbol) [0x0072093C]
        (No symbol) [0x0071A536]
        (No symbol) [0x006F82DC]
        (No symbol) [0x006F93DD]
        GetHandleVerifier [0x00A9AABD+2539405]
        GetHandleVerifier [0x00ADA78F+2800735]
        GetHandleVerifier [0x00AD456C+2775612]
        GetHandleVerifier [0x008C51E0+616112]
        (No symbol) [0x007D5F8C]
        (No symbol) [0x007D2328]
        (No symbol) [0x007D240B]
        (No symbol) [0x007C4FF7]
        BaseThreadInitThunk [0x775BFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C17C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77C17C3E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\oldZ\Paradise_for_abuztrade\All_my_bots\Projects\_temp\sb\test.py", line 3, in <module>
    driver = Driver()
  File "C:\Python310\lib\site-packages\seleniumbase\plugins\driver_manager.py", line 397, in Driver
    driver = browser_launcher.get_driver(
  File "C:\Python310\lib\site-packages\seleniumbase\core\browser_launcher.py", line 1261, in get_driver
    return get_local_driver(
  File "C:\Python310\lib\site-packages\seleniumbase\core\browser_launcher.py", line 3385, in get_local_driver
    return webdriver.Chrome()
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 120.0.6099.217 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0083A813+48355]
        (No symbol) [0x007CC4B1]
        (No symbol) [0x006D5358]
        (No symbol) [0x006F61AC]
        (No symbol) [0x006F1EF3]
        (No symbol) [0x006F0579]
        (No symbol) [0x00720C55]
        (No symbol) [0x0072093C]
        (No symbol) [0x0071A536]
        (No symbol) [0x006F82DC]
        (No symbol) [0x006F93DD]
        GetHandleVerifier [0x00A9AABD+2539405]
        GetHandleVerifier [0x00ADA78F+2800735]
        GetHandleVerifier [0x00AD456C+2775612]
        GetHandleVerifier [0x008C51E0+616112]
        (No symbol) [0x007D5F8C]
        (No symbol) [0x007D2328]
        (No symbol) [0x007D240B]
        (No symbol) [0x007C4FF7]
        BaseThreadInitThunk [0x775BFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C17C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77C17C3E+238]
```

**Comment by mdmintz** [comment]
You're using an old version of SeleniumBase. Your `Line 397` of `driver_manager.py` is on `Line 463` of the latest version. https://github.com/seleniumbase/SeleniumBase/blob/31020e4ae9644596460e9606312f94bc420aff51/seleniumbase/plugins/driver_manager.py#L463

**Comment by makarworld** [comment]
yes, sorry, my bad

> You're using an old version of SeleniumBase. Your `Line 397` of `driver_manager.py` is on `Line 463` of the latest version.
> 
> https://github.com/seleniumbase/SeleniumBase/blob/31020e4ae9644596460e9606312f94bc420aff51/seleniumbase/plugins/driver_manager.py#L463
