### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist 

### ISSUE THREAD

**Issue by gitkdp2844** [seleniumbase/SeleniumBase#2489]
**My code which i am trying to open browser and loading the URL. but here browser is opening but url is not loaded. it is blank** 

```
from selenium import webdriver
import time

#path = 'C:/Users/Pasupuleti.Chandra/Downloads/edgedriver/msedgedriver.exe'
options = webdriver.EdgeOptions()
driver = webdriver.Edge(options=options)
print("url opening============================================================================================================================")
driver.get('https://www.geeksforgeeks.com')
print("url opening============================================================================================================================")

time.sleep(540)
```
![error](https://github.com/seleniumbase/SeleniumBase/assets/60216417/0ce7ae08-c307-4e38-8435-f45c703e618b)

![image](https://github.com/seleniumbase/SeleniumBase/assets/60216417/014bca4c-3b8c-4287-a1f1-6aa71c750936)

**Comment by mdmintz** [comment]
It doesn't look like you've used `seleniumbase` at all in your example.

Try the code below after `"pip install seleniumbase"`: (For various Edge tests)

```python
from seleniumbase import Driver

driver = Driver(browser="edge")
try:
    driver.open("seleniumbase.io/simple/login")
    driver.type("#username", "demo_user")
    driver.type("#password", "secret_pass")
    driver.click('a:contains("Sign in")')
    driver.assert_exact_text("Welcome!", "h1")
    driver.assert_element("img#image1")
    driver.highlight("#image1")
    driver.click_link("Sign out")
    driver.assert_text("signed out", "#top_message")
finally:
    driver.quit()
```

```python
from seleniumbase import Driver

driver = Driver(browser="edge")
try:
    driver.open("seleniumbase.io/apps/calculator")
    driver.click('[id="4"]')
    driver.click('[id="2"]')
    driver.assert_text("42", "#output")
    driver.highlight("#output", loops=6)
finally:
    driver.quit()
```

```python
driver = Driver(browser="edge")
try:
    driver.open("seleniumbase.github.io/demo_page")
    driver.highlight("h2")
    driver.type("#myTextInput", "Automation")
    driver.click("#checkBox1")
    driver.highlight("img", loops=6)
finally:
    driver.quit()
```

See [SeleniumBase/help_docs/syntax_formats.md](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/syntax_formats.md) for more ways of structuring tests.

**Comment by gitkdp2844** [comment]
still facing the same thing


![image](https://github.com/seleniumbase/SeleniumBase/assets/60216417/3e74f03a-2224-4ac2-8b8e-acff975300e3)


Microsoft Edge Driver not found. Getting it now:

*** edgedriver to download = 121.0.2277.112

Downloading edgedriver_win64.zip from:
https://msedgedriver.azureedge.net/121.0.2277.112/edgedriver_win64.zip ...
Download Complete!

Extracting ['msedgedriver.exe'] from edgedriver_win64.zip ...
Unzip Complete!

The file [msedgedriver.exe] was saved to:
C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\drivers\msedgedriver.exe

Making [msedgedriver.exe 121.0.2277.112] executable ...
[msedgedriver.exe 121.0.2277.112] is now ready for use!

Traceback (most recent call last):
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 2765, in get_local_driver
    driver = Edge(service=service, options=edge_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
        GetHandleVerifier [0x00007FF7B498B892+60738]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4917B32+233058]
        (No symbol) [0x00007FF7B472AE0B]
        (No symbol) [0x00007FF7B4768314]
        (No symbol) [0x00007FF7B476192D]
        (No symbol) [0x00007FF7B475DB18]
        (No symbol) [0x00007FF7B47A7389]
        (No symbol) [0x00007FF7B479C233]
        (No symbol) [0x00007FF7B476D568]
        (No symbol) [0x00007FF7B476C394]
        (No symbol) [0x00007FF7B476D101]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7B4B47D2C+1072924]
        (No symbol) [0x00007FF7B47F0F45]
        (No symbol) [0x00007FF7B4888F6C]
        (No symbol) [0x00007FF7B4880A5D]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7B4B46773+1067363]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4921A88+273848]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B491C794+252612]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B491C8C2+252914]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4912EC1+213489]
        BaseThreadInitThunk [0x00007FFDED6C257D+29]
        RtlUserThreadStart [0x00007FFDEE58AA58+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Pasupuleti.Chandra\Desktop\test.py", line 4, in <module>
    driver = Driver(browser="edge")
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\plugins\driver_manager.py", line 488, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 1594, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 2794, in get_local_driver
    driver = Edge(service=service, options=edge_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Pasupuleti.Chandra\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00007FF7B498B892+60738]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4917B32+233058]
        (No symbol) [0x00007FF7B472AC43]
        (No symbol) [0x00007FF7B4717720]
        (No symbol) [0x00007FF7B47688F1]
        (No symbol) [0x00007FF7B4761B58]
        (No symbol) [0x00007FF7B475DB18]
        (No symbol) [0x00007FF7B47A7389]
        (No symbol) [0x00007FF7B479C233]
        (No symbol) [0x00007FF7B476D568]
        (No symbol) [0x00007FF7B476C394]
        (No symbol) [0x00007FF7B476D101]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7B4B47D2C+1072924]
        (No symbol) [0x00007FF7B47F0F45]
        (No symbol) [0x00007FF7B4888F6C]
        (No symbol) [0x00007FF7B4880A5D]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7B4B46773+1067363]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4921A88+273848]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B491C794+252612]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B491C8C2+252914]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7B4912EC1+213489]
        BaseThreadInitThunk [0x00007FFDED6C257D+29]
        RtlUserThreadStart [0x00007FFDEE58AA58+40]

**Comment by gitkdp2844** [comment]
![image](https://github.com/seleniumbase/SeleniumBase/assets/60216417/dd7dad10-274f-4caa-bfd4-b5dc4304eab2)

**Comment by mdmintz** [comment]
This message: `"DevTools remote debugging is disallowed by the system admin."` means that Selenium is being blocked by your System Administrator. Check with them about getting fewer restrictions so that you can run browser automation.
