### ISSUE TITLE
Unclear exceptions

### ISSUE THREAD

**Issue by boludoz** [seleniumbase/SeleniumBase#2567]
```
from seleniumbase import SB
from selenium.common.exceptions import NoSuchElementException

def open_the_turnstile_page(sb):
    sb.driver.uc_open_with_reconnect(
        "https://seleniumbase.io/apps/turnstile", reconnect_time=2.5,
    )

def click_turnstile_and_verify(sb):
    sb.driver.uc_switch_to_frame("iframe")
    sb.driver.uc_click("span.marka", timeout=0)
    sb.assert_element("img#captcha-success", timeout=3.33)

with SB(uc=True, test=True) as sb:
    open_the_turnstile_page(sb)
    try:
        click_turnstile_and_verify(sb)
    except NoSuchElementException:
        print("\nSelenium wasn't detected!")
        
    sb.set_messenger_theme(location="top_left")
    sb.post_message("Selenium wasn't detected!", duration=3)
```

```
=================== {tempCodeRunnerFile.python:15:SB} starts ===================

Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 122.0.6261.94 (Latest Stable) 

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.94/win64/chromedriver-win64.zip ...
Download Complete!

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\seleniumbase\plugins\sb_manager.py", line 897, in SB
    yield sb
  File "f:\C-proyects\bot_pagostore\tempCodeRunnerFile.python", line 18, in <module>
    click_turnstile_and_verify(sb)
  File "f:\C-proyects\bot_pagostore\tempCodeRunnerFile.python", line 12, in click_turnstile_and_verify
    sb.driver.uc_click("span.marka", timeout=0)
  File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 3607, in <lambda>
    driver.uc_click = lambda *args, **kwargs: uc_click(
                                              ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 449, in uc_click
    element = driver.wait_for_element(selector, by=by, timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\core\sb_driver.py", line 98, in wait_for_element
    return page_actions.wait_for_element(self.driver, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 1732, in wait_for_element
    return wait_for_element_visible(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 508, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 266, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message: 
 Element {span.marka} was not present after 0 seconds!


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\seleniumbase\plugins\sb_manager.py", line 924, in SB
    sb.tearDown()
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\base_case.py", line 15948, in tearDown
    log_helper.log_test_failure_data(
  File "C:\Python312\Lib\site-packages\seleniumbase\core\log_helper.py", line 289, in log_test_failure_data
    log_file = codecs.open(basic_file_path, "w+", "utf-8")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 906, in open
OSError: [Errno 22] Invalid argument: 'latest_logs\\SB\n    yield sb\n  File "f:\\C-proyects\\bot_pagostore\\tempCodeRunnerFile.line_15\\basic_test_info.txt'
********** ERROR: The test AND the tearDown() FAILED!
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\seleniumbase\plugins\sb_manager.py", line 897, in SB
    yield sb
  File "f:\C-proyects\bot_pagostore\tempCodeRunnerFile.python", line 18, in <module>
    click_turnstile_and_verify(sb)
  File "f:\C-proyects\bot_pagostore\tempCodeRunnerFile.python", line 12, in click_turnstile_and_verify
    sb.driver.uc_click("span.marka", timeout=0)
  File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 3607, in <lambda>
    driver.uc_click = lambda *args, **kwargs: uc_click(
                                              ^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\core\browser_launcher.py", line 449, in uc_click
    element = driver.wait_for_element(selector, by=by, timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\core\sb_driver.py", line 98, in wait_for_element
    return page_actions.wait_for_element(self.driver, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 1732, in wait_for_element
    return wait_for_element_visible(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 508, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "C:\Python312\Lib\site-packages\seleniumbase\fixtures\page_actions.py", line 266, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message: 
 Element {span.marka} was not present after 0 seconds!
============== {tempCodeRunnerFile.python:15:SB} failed in 12.85s ==============
```

**Comment by boludoz** [comment]
My proposal is that Selenium native exceptions be allowed to be used for better compatibility and ease of use.

**Comment by boludoz** [comment]
Finally my solution was:
`from seleniumbase.common.exceptions import NoSuchElementException`

I really appreciate your work

**Comment by mdmintz** [comment]
1. You set `timeout=0`. The `timeout` should always be greater than 0 because otherwise the element is never searched.
2. You need to upgrade to a newer version of SeleniumBase because the Chromedriver team changed download locations.

**Comment by boludoz** [comment]
> 1. You set `timeout=0`. The `timeout` should always be greater than 0 because otherwise the element is never searched.
> 2. You need to upgrade to a newer version of SeleniumBase because the Chromedriver team changed download locations.

This is intentional

**Comment by boludoz** [comment]
Tip: I have realized that xpaths can be combined.
