### ISSUE TITLE
conflict with requirement flake8

### ISSUE THREAD

**Issue by dowenb** [seleniumbase/SeleniumBase#276]
== Steps ==
Fresh install of Python 3.7.2 - installed on Windows 10 for "all users"
successfully cloned a fresh copy of seleniumbase
run \SeleniumBase>pip install -U -r requirements.txt

== Expected ==
Requirements are installed or updated

== Actual ==
Error:
 "pip._vendor.pkg_resources.ContextualVersionConflict: (flake8 3.6.0 (c:\program files (x86)\python37-32\lib\site-packages), Requirement.parse('flake8==3.7.5'), {'seleniumbase'})"

== Full error ==
e:\dev\SeleniumBase>pip install -U -r requirements.txt
Obtaining file:///E:/dev/SeleniumBase (from -r requirements.txt (line 23))
Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\req\req_install.py", line 391, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (flake8 3.6.0 (c:\program files (x86)\python37-32\lib\site-packages), Requirement.parse('flake8==3.7.5'), {'seleniumbase'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 176, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\resolve.py", line 226, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\operations\prepare.py", line 386, in prepare_editable_requirement
    req.check_if_exists(use_user_site)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_internal\req\req_install.py", line 402, in check_if_exists
    self.req.name
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\program files (x86)\python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (flake8 3.6.0 (c:\program files (x86)\python37-32\lib\site-packages), Requirement.parse('flake8==3.7.5'), {'seleniumbase'})

**Comment by dowenb** [comment]
I've tried installing flake8 outside the requirements.txt

e:\dev\SeleniumBase>pip install flake8
Requirement already satisfied: flake8 in c:\program files (x86)\python37-32\lib\site-packages (3.6.0)
Requirement already satisfied: pycodestyle<2.5.0,>=2.4.0 in c:\program files (x86)\python37-32\lib\site-packages (from flake8) (2.4.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\program files (x86)\python37-32\lib\site-packages (from flake8) (0.6.1)
Requirement already satisfied: pyflakes<2.1.0,>=2.0.0 in c:\program files (x86)\python37-32\lib\site-packages (from flake8) (2.0.0)
Requirement already satisfied: setuptools>=30 in c:\program files (x86)\python37-32\lib\site-packages (from flake8) (40.8.0)

**Comment by mdmintz** [comment]
If you upgrade flake8 with ``pip install -U flake8`` , does that solve your issue?

**Comment by mdmintz** [comment]
You can get all the latest requirements with ``pip install -U requirements.txt``

**Comment by mdmintz** [comment]
When you pull a newer version of SeleniumBase, the requirements may have changed, and therefore ``pip install -U -r requirements.txt`` gets you back up-to-date.

**Comment by mdmintz** [comment]
@dowenb Let me know if you're still having any issues with anything SeleniumBase. 😄
