### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4) on sb.uc_gui_handle_cf

### ISSUE THREAD

**Issue by moadennagi** [seleniumbase/SeleniumBase#2937]
**Environment:**
Linux ubuntu 22.04
python3.10
seleniumbase==4.28.5

**Steps to reproduce**
On a fresh install, run the following example the turnstyle example https://seleniumbase.io/help_docs/uc_mode/#uc-mode
```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://seleniumbase.io/apps/turnstile"
    sb.uc_open_with_reconnect(url, reconnect_time=2)
    sb.uc_gui_handle_cf()
    sb.assert_element("img#captcha-success", timeout=3)
    sb.set_messenger_theme(location="top_left")
    sb.post_message("SeleniumBase wasn't detected", duration=3)
```
I get the following error:
```
Using cached pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
Installing collected packages: pytweening, python3-Xlib, pyrect, pyperclip, pymsgbox, pygetwindow, Pillow, mouseinfo, pyscreeze, pyautogui
Successfully installed Pillow-10.4.0 mouseinfo-0.1.3 pyautogui-0.9.54 pygetwindow-0.0.9 pymsgbox-1.0.9 pyperclip-1.9.0 pyrect-0.2.0 pyscreeze-0.1.30 python3-Xlib-0.15 pytweening-1.2.0
Traceback (most recent call last):
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/seleniumbase/plugins/sb_manager.py", line 964, in SB
    yield sb
  File "/home/mennagi/Documents/selenium/turnstyle.py", line 6, in <module>
    sb.uc_gui_handle_cf()
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 4333, in <lambda>
    lambda *args, **kwargs: uc_gui_handle_cf(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 909, in uc_gui_handle_cf
    import pyautogui
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/Xlib/display.py", line 89, in __init__
    # Translations for keysyms to strings.
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/Xlib/display.py", line 71, in __init__
    # don't cache NONE responses in case someone creates this later
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/Xlib/protocol/display.py", line 84, in __init__
    self.send_active = 0
ValueError: not enough values to unpack (expected 5, got 4)
```
The issue only happens the first time I run the example, the example runs ok afterwards

**Comment by mdmintz** [comment]
I'm not able to reproduce this issue on Linux with a fresh install. Might be something else going on with your environment. Since you mentioned that it works after the first time you run the example, you may want to put in a dummy method so that the first time doesn't occur for your real scripts.

**Comment by jimmy927** [comment]
I am having the same issue. It looks like an mouseinfo maybe as seleniumbase fails when importing mouseinfo excacty like above.


```
>>> with SB(uc=True) as sb:
...     pass
...

PyAutoGUI is required for UC Mode on Linux! Installing now...
Requirement already satisfied: pyautogui==0.9.54 in /usr/local/lib/python3.9/dist-packages (0.9.54)
Requirement already satisfied: python3-Xlib in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (0.15)
Requirement already satisfied: pymsgbox in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (1.0.9)
Requirement already satisfied: pytweening>=1.0.4 in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (1.2.0)
Requirement already satisfied: pyscreeze>=0.1.21 in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (1.0.1)
Requirement already satisfied: pygetwindow>=0.0.5 in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (0.0.9)
Requirement already satisfied: mouseinfo in /usr/local/lib/python3.9/dist-packages (from pyautogui==0.9.54) (0.1.3)
Requirement already satisfied: pyrect in /usr/local/lib/python3.9/dist-packages (from pygetwindow>=0.0.5->pyautogui==0.9.54) (0.2.0)
Requirement already satisfied: Pillow>=9.2.0 in /usr/local/lib/python3.9/dist-packages (from pyscreeze>=0.1.21->pyautogui==0.9.54) (9.5.0)
Requirement already satisfied: pyperclip in /usr/local/lib/python3.9/dist-packages (from mouseinfo->pyautogui==0.9.54) (1.9.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/fixtures/base_case.py", line 13968, in __activate_virtual_display_as_needed
    import pyautogui
  File "/usr/local/lib/python3.9/dist-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.9/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 89, in __init__
    # Translations for keysyms to strings.
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 71, in __init__
    # don't cache NONE responses in case someone creates this later
  File "/usr/local/lib/python3.9/dist-packages/Xlib/protocol/display.py", line 84, in __init__
    self.send_active = 0
ValueError: not enough values to unpack (expected 5, got 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/plugins/sb_manager.py", line 1211, in SB
    sb.setUp()
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/fixtures/base_case.py", line 15021, in setUp
    self.__activate_virtual_display_as_needed()
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/fixtures/base_case.py", line 13987, in __activate_virtual_display_as_needed
    import pyautogui
  File "/usr/local/lib/python3.9/dist-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.9/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 89, in __init__
    # Translations for keysyms to strings.
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 71, in __init__
    # don't cache NONE responses in case someone creates this later
  File "/usr/local/lib/python3.9/dist-packages/Xlib/protocol/display.py", line 84, in __init__
    self.send_active = 0
ValueError: not enough values to unpack (expected 5, got 4)
>>>


```
But it fails when just importing mouseinfo

See here:
```
>>> import mouseinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 89, in __init__
    # Translations for keysyms to strings.
  File "/usr/local/lib/python3.9/dist-packages/Xlib/display.py", line 71, in __init__
    # don't cache NONE responses in case someone creates this later
  File "/usr/local/lib/python3.9/dist-packages/Xlib/protocol/display.py", line 84, in __init__
    self.send_active = 0
ValueError: not enough values to unpack (expected 5, got 4)
>>> os.environ['DISPLAY']
':1005'
>>>
```

same issue described here:

https://stackoverflow.com/questions/79175347/use-seleniumbase-in-uc-mode-in-google-colab

**Comment by jimmy927** [comment]
Problem disappered when upgrading from python 3.9 to 3.12
Suspecting some kind of Xlib compatibility.
Like Xlib added a parameter but older python-xlib or python3-Xlib not adjusted yet or similar.

Definetly not really a seleniumbase issue.

**Comment by tamvm** [comment]
> Problem disappered when upgrading from python 3.9 to 3.12 Suspecting some kind of Xlib vs. python compatibility issue. Like Xlib added a parameter but older python-xlib or python3-Xlib not adjusted yet or similar.
> 
> Definetly not really a seleniumbase issue.

I tried docker python:3.12-slim as well but it's still failing with same error :(

**Comment by Qolum** [comment]
I have the same error. Has someone found a fix for this?
I use the latest Python version.

**Comment by mdmintz** [comment]
Upgrade your Python version. It didn't work on 3.9, but it did work on 3.12. (Maybe also works on versions between those)

**Comment by Alexei17** [comment]
Doesn't work for 3.12

**Comment by Alexei17** [comment]
I asked ChatGPT and it worked after these suggestion. Hope this helps.

The error message you're encountering is due to a compatibility issue involving PyAutoGUI, mouseinfo, and the Xlib library on your Linux environment.
Why this happens:

    PyAutoGUI requires a graphical environment (X display) to function correctly on Linux.

    The error ValueError: not enough values to unpack (expected 5, got 4) is usually triggered by an internal mismatch or unexpected response from the python-xlib library or the environment's display variable ($DISPLAY).

How to resolve this:

1. Verify the display environment:

Make sure you have an active X server (graphical display). If you're running this in a headless environment (e.g., server or CI), you'll need a virtual display server like Xvfb.

sudo apt update
sudo apt install xvfb

Then start it manually:

Xvfb :99 -screen 0 1024x768x24 &
export DISPLAY=:99

2. Ensure dependencies are correctly installed:

Update your Python packages:

pip install --upgrade seleniumbase pyautogui mouseinfo python-xlib

3. If you're using SeleniumBase UC mode, manually install undetected-chromedriver:

pip install undetected-chromedriver

Then set UC mode accordingly in your SeleniumBase tests.
Example working configuration:

sudo apt update
sudo apt install xvfb python3-tk python3-dev python3-pip
Xvfb :99 -screen 0 1280x1024x24 &
export DISPLAY=:99
pip install seleniumbase pyautogui mouseinfo python-xlib undetected-chromedriver

Then run your script again.
