### ISSUE TITLE
Error using asyncio : urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45117): Max retries exceeded with url: /session/491128701b5eb54be7e27643b0d08ccc/execute/sync

### ISSUE THREAD

**Issue by moadennagi** [seleniumbase/SeleniumBase#2944]
Is there any support for asyncio ? 

**Environment**
Linux Ubuntu 22.04
seleniumbase==4.28.6

**To reproduce**
I am gathering a list of coroutines to be executed with `asyncio.gather`, here is a minimal code:
```python
  
    async def go_to_page(sb, url):
        sb.uc_open_with_reconnect(url, 6)


    async def main(urls):
        tasks = []
        urls = [...]
        for url in urls:
            with SB(uc=True, test=True, incognito=True) as sb:
                tasks.append(go_to_page(sb, url))
        await asyncio.gather(*tasks)


    asyncio.run(main(urls))
```
This code gives the following error
```
Traceback (most recent call last):
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x74abc4668400>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mennagi/Documents/selenium/raw_test_tls_rabat.py", line 130, in <module>
    asyncio.run(main(urls))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mennagi/Documents/selenium/raw_test_tls_rabat.py", line 127, in main
    await asyncio.gather(*tasks)
  File "/home/mennagi/Documents/selenium/raw_test_tls_rabat.py", line 119, in go_to_page
    sb.uc_open_with_reconnect(url, 6)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 4308, in <lambda>
    lambda *args, **kwargs: uc_open_with_reconnect(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 473, in uc_open_with_reconnect
    driver.execute_script(script)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 352, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 302, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py", line 322, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 144, in request
    return self.request_encode_body(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/home/mennagi/Documents/selenium/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52717): Max retries exceeded with url: /session/3a8eca95d82b072dbf7b8c4517511945/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x74abc4668400>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by mdmintz** [comment]
You **cannot** launch multiple UC Mode web browsers at the same time, as that will lead to port conflicts. However, once the browsers are launched, you **can** have multiple scripts running on multiple browsers at the same time.

There are some multithreading strategies in the [UC Mode Documentation](https://github.com/seleniumbase/SeleniumBase/blob/master/help_docs/uc_mode.md) if you don't want to space out the launching of the browsers yourself.
