### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver'

### ISSUE THREAD

**Issue by LostInDarkMath** [seleniumbase/SeleniumBase#3274]
Hi there,
when I try to run my Python project based on `SeleniumBase` I get the following error:

```
Traceback (most recent call last):
  File "/opt/src/run.py", line 26, in <module>
    results = load_results(search_term=search_term, keyword=keyword, min_price=min_price)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/src/main.py", line 19, in load_results
    data = load_data(url=url)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/src/main.py", line 30, in load_data
    with Driver(
         ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 789, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 2765, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 4767, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 314, in __init__
    super().__init__(options=options, service=service_)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver'
```

The cause of the issue is, that I'm on the `armv7l` system architecture. So my question is: What is the best way to fix this? I'm pretty new to Selenium and I do not found a matching Chrome driver on https://googlechromelabs.github.io/chrome-for-testing/

What are the best practices for this case?

**Comment by mdmintz** [comment]
There's a workaround to patching that driver (since Raspberry Pi architecture it not part of [chrome-for-testing](https://googlechromelabs.github.io/chrome-for-testing/)).

See https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/917#issuecomment-1792521488.

Once your driver is patched using that, rename it to `uc_driver`, and put it in your `seleniumbase/drivers/` folder.
