### ISSUE TITLE
Need about Profile Chrome

### ISSUE THREAD

**Issue by thienha1** [seleniumbase/SeleniumBase#3361]
How to run uc_driver with UC mode as specific profile
Like:
```
from seleniumbase import Driver
from seleniumbase import undetected

user_data_dir = "C:\\Users\\ripssas\\AppData\\Local\\Google\\Chrome\\User Data"
option = undetected.ChromeOptions()
option.add_argument(r"--user-data-dir=user_data_dir") 
option.add_argument(r'--profile-directory=Profile 2')
driver = Driver(uc=True)
driver = Driver.Chrome(options = option)
url = "https://freebitco.in"
driver.uc_open_with_reconnect(url, 4)
driver.uc_gui_click_captcha()
driver.quit()

```
I tried about and got this error
```
PS C:\Users\ripas\Downloads\Web LAB\Botasaurus Firefox> py "3rd Bot.py"
Traceback (most recent call last):
  File "C:\Users\ripas\Downloads\Web LAB\Botasaurus Firefox\3rd Bot.py", line 10, in <module>
    driver = webdriver.Chrome(options = option)
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 241, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\ripas\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: crashed.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
        GetHandleVerifier [0x00007FF7EBF9FB05+28789]
        (No symbol) [0x00007FF7EBF086E0]
        (No symbol) [0x00007FF7EBDA592A]
        (No symbol) [0x00007FF7EBDE01E4]
        (No symbol) [0x00007FF7EBDDBC59]
        (No symbol) [0x00007FF7EBE2A77C]
        (No symbol) [0x00007FF7EBE29D60]
        (No symbol) [0x00007FF7EBE1F1E3]
        (No symbol) [0x00007FF7EBDEA938]
        (No symbol) [0x00007FF7EBDEBAA1]
        GetHandleVerifier [0x00007FF7EC2D933D+3410093]
        GetHandleVerifier [0x00007FF7EC2EE7DD+3497293]
        GetHandleVerifier [0x00007FF7EC2E2A73+3448803]
        GetHandleVerifier [0x00007FF7EC067BBB+848171]
        (No symbol) [0x00007FF7EBF13C3F]
        (No symbol) [0x00007FF7EBF0F6E4]
        (No symbol) [0x00007FF7EBF0F87D]
        (No symbol) [0x00007FF7EBEFED49]
        BaseThreadInitThunk [0x00007FF8A78A53E0+16]
        RtlUserThreadStart [0x00007FF8A838485B+43]
```
I have no solution about this due to i have little experience about this

**Comment by mdmintz** [comment]
Looks like a duplicate of https://github.com/seleniumbase/SeleniumBase/issues/3138#issuecomment-2355712047.

**Comment by thienha1** [comment]
" The best option there is to create a new user-data-dir " , SeleniumBase has any command that create user data dir? Also, im using Windows 11, not Linux!!

**Comment by mdmintz** [comment]
Set the `user_data_dir` arg to have SeleniumBase automatically create it under that name:
https://github.com/seleniumbase/SeleniumBase/blob/05bb5657addf337944c1f954706ca1623e8cc559/seleniumbase/plugins/sb_manager.py#L74

**Comment by thienha1** [comment]
It works, tks
