### ISSUE TITLE
Unable to accept alert immediately after opening page

### ISSUE THREAD

**Issue by jrtitus** [seleniumbase/SeleniumBase#74]
I have a simple case where there is a JavaScript alert that is displayed immediately upon opening a page:

```python
from seleniumbase import BaseCase

class LoginTest(BaseCase):

    def test_0(self):
        self.open("http://192.168.12.1")
        self.wait_for_and_switch_to_alert()
        self.wait_for_and_accept_alert()
```

Unfortunately this does not work and results in an `UnexpectedAlertPresentException`:

```
C:\selenium>nosetests login.py --with-selenium --with-testing_base --report
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\nosetests.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\nose\core.py", line 121, in __init__
    **extra_args)
  File "c:\python27\lib\unittest\main.py", line 95, in __init__
    self.runTests()
  File "c:\python27\lib\site-packages\nose\core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "c:\python27\lib\site-packages\nose\core.py", line 62, in run
    test(result)
  File "c:\python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "c:\python27\lib\site-packages\nose\suite.py", line 224, in run
    test(orig)
  File "c:\python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "c:\python27\lib\site-packages\nose\suite.py", line 224, in run
    test(orig)
  File "c:\python27\lib\site-packages\nose\suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "c:\python27\lib\site-packages\nose\suite.py", line 224, in run
    test(orig)
  File "c:\python27\lib\site-packages\nose\case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "c:\python27\lib\site-packages\nose\case.py", line 138, in run
    result.addError(self, err)
  File "c:\python27\lib\site-packages\nose\proxy.py", line 131, in addError
    plugins.addError(self.test, err)
  File "c:\python27\lib\site-packages\nose\plugins\manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "c:\python27\lib\site-packages\nose\plugins\manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "c:\python27\lib\site-packages\nose\plugins\manager.py", line 334, in addError
    return self.plugin.addError(test.test, err, capt)
  File "c:\python27\lib\site-packages\seleniumbase\plugins\base_plugin.py", line 169, in addError
    self.__log_all_options_if_none_specified(test)
  File "c:\python27\lib\site-packages\seleniumbase\plugins\base_plugin.py", line 123, in __log_all_options_if_none_specified
    log_helper.log_screenshot(test_logpath, test.driver)
  File "c:\python27\lib\site-packages\seleniumbase\core\log_helper.py", line 10, in log_screenshot
    driver.get_screenshot_as_file(screenshot_path)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 800, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 819, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 829, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : Restricted use. Authorized users only.}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64)
```

This pure Selenium equivalent works:

```python
from selenium import webdriver
from selenium.webdriver.common.alert import Alert

driver = webdriver.Chrome()
driver.get("http://192.168.12.1")
Alert(driver).accept()
```

Thanks in advance!

**Comment by mdmintz** [comment]
Hi! The url in your example isn't loading for me, but for the code, all you need is:
```self.wait_for_and_accept_alert()```

The other `self.wait_for_and_switch_to_alert()` should not be needed since the other call already waits for and accepts the alert present. Does that help? If not, give me an example with a publicly accessible url and I will track down and fix the problem. Thanks!

**Comment by jrtitus** [comment]
Hi @mdmintz! Thanks for the quick response. I should have mentioned that I also tried not using the `switch_to` function, but received the same result. I'll get back to you with a public URL - this one was from a pi on my local network.

**Comment by mdmintz** [comment]
Hi @jrtitus , Try it now. I made some fixes to work around Geckodriver bugs when using Firefox, which includes another fix when using any browser. If it's still broken, send me the public URL that reproduces the issue. Thanks!

**Comment by jrtitus** [comment]
Awesome! Works perfectly now with Selenium base 1.3.3. Thanks!
