### ISSUE TITLE
Multi-threading issues when assert_no_404_errors() finds broken links

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#788]
Multi-threading issues when ``self.assert_no_404_errors()`` finds broken links.
This is caused by raising an exception while in a multiprocessing thread.

```python
Exception ignored in: <function Pool.__del__ at 0x105d414c0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```

To get around this issue, the exception for finding 404 errors should only be raised after the multiprocessing threads all complete when calling ``self.assert_no_404_errors()``.

**Comment by mdmintz** [comment]
Fixed by https://github.com/seleniumbase/SeleniumBase/releases/tag/v1.52.6
